#!/bin/bash

# ru-sftp — Convenience script for SFTPing into Rutgers computers

# Usage: ru-sftp [NAME]

# If NAME is '1', '2', '3', or empty, attempts to SFTP into ilabNAME.cs.rutgers.edu.
# Otherwise, attempts to SFTP into NAME.cs.rutgers.edu.
#     If that fails, attempts to SFTP into NAME.rutgers.edu.

# Examples: `ru-sftp 3`, `ru-sftp patterns`, `ru-sftp nbcs`

USERNAME='CHANGEME'

if [[ $1 == '' || $1 =~ ^[1-3]$ ]]; then
  sftp $USERNAME@ilab$1.cs.rutgers.edu
else
  sftp $USERNAME@$1.cs.rutgers.edu 2>/dev/null ||
    sftp $USERNAME@$1.rutgers.edu 2>/dev/null ||
    printf 'All connections failed\n'
fi
